// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgincrppujmwejqbibim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnaW5jcnBwdWptd2VqcWJpYmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTcwMjgsImV4cCI6MjA1ODQ5MzAyOH0.jMNpvVkH51GLO4yFrisAePLSnsiotgOVkbbJFrpRXos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);